Vault 플러그인에 Hook하기
MineFactory-Resource/Uconomy pull request #2
Opened 2022-09-07 11:59 UTC by Seokhun-Yang

2022-09-12 11:24 UTC, kari0707 commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                            if ((long) economyManager.getBalance(player) < Long.parseLong(args[2])) {
이런식으로 타입을 long 으로 형변환 해서 사용하는 이유가 뭔가요?

2022-09-12 11:24 UTC, kari0707 commented on src/main/java/net/teamuni/economy/Uconomy.java
> +    public static Uconomy getInstance;
메인 클래스의 인스턴스를 담은 변수를 public static 으로 사용하게 되면 외부에서 접근이 가능해서 플러그인이 안전하지 않습니다. private 으로 접근제어자를 바꿔주고, static Getter를 만들어 사용해주시기 바랍니다.

다른 플러그인을 참고하며, 싱글톤 패턴에 대해 공부해보시는 게 좋을 거 같습니다

2022-09-12 11:27 UTC, tjrhuni commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                            if ((long) economyManager.getBalance(player) < Long.parseLong(args[2])) {
Economy 클래스의 getBalance() 메소드의 리턴타입이 double이기 때문입니다

2022-09-12 11:28 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +    public static Uconomy getInstance;
다른 플러그인을 참고하려 했는데 어떤 플러그인을 참고하면 좋을지 몰랐습니다.. 방향을 제시해주시면 감사하겠습니다

2022-09-12 11:29 UTC, kari0707 commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                            if ((long) economyManager.getBalance(player) < Long.parseLong(args[2])) {
double 타입을 long으로 변환하는 이유가 부동소수점 때문인가요?

2022-09-12 11:29 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                            if ((long) economyManager.getBalance(player) < Long.parseLong(args[2])) {
네 맞습니다

2022-09-12 11:32 UTC, kari0707 commented on src/main/java/net/teamuni/economy/Uconomy.java
> +    public static Uconomy getInstance;
https://github.com/MineFactory-Resource/GunsCS/blob/main/src/main/java/net/teamuni/gunscs/GunsCS.java

일반적인 싱글톤 활용입니당. 외에도 Parkour 플러그인이나 GunsCore 플러그인의 메인 클래스들 처럼 활용할 수 있습니다

2022-09-12 11:32 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +    public static Uconomy getInstance;
감사합니다! 해당 플러그인을 참고하면서 싱글톤 패턴에 대해 공부해보도록 하겠습니다

2022-09-12 11:33 UTC, kari0707 commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                            if ((long) economyManager.getBalance(player) < Long.parseLong(args[2])) {
long은 부동 소수점이 아닌 값을 저장하는 걸 처음알았네요..ㅋㅋ 배워갑니당

2022-09-13 09:20 UTC, kari0707 approved these changes

2022-09-13 09:21 UTC, Fade-Jung approved these changes

2022-09-13 10:50 UTC, LesserJang requested changes
getBalance 메소드를 제외한 모든 메소드를 그냥 null 이나 false 가 반환되도록 해놓으셨는데, Vault API JavaDocs 에서 각 메소드에 대한 기능 설명을 읽고 메소드들을 구현해주세요. 이러면 다른 플러그인에서 플레이어 돈을 가져오는 것 밖에 할 수 없어요.

2022-09-13 10:51 UTC, Seokhun-Yang commented
알겠습니당

2022-09-15 11:58 UTC, LesserJang requested changes

2022-09-15 11:58 UTC, LesserJang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +@Getter
Getter의 영향을 받을만한 변수들이 없어요. 지워주세요

2022-09-15 11:58 UTC, LesserJang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +        return Thread.currentThread().getStackTrace()[2].getMethodName();
어.. 메소드 이름을 왜 반환시키는건가요..? 아무리 생각해도 API에서 메소드 이름을 사용하는 일은 없을 것 같은데요..

2022-09-15 11:58 UTC, LesserJang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +        assert player != null;
assert문은 이럴 때 쓰는게 아닙니다.. assert는 진짜 이게 null이 뜰 수 없을 때 사용하는거에요. null을 체크하는 용도가 아닙니다. 만약 해당 플레이어가 서버에 접속중이지 않으면 바로 NPE 뜰거에요. if 문으로 null 체크 해주세요.

2022-09-15 11:58 UTC, LesserJang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +    }
Vault API에서 돈을 주고 받는 행위는 모두 이 메소드를 통해서 이루어지는데 이걸 그냥 null을 반환해버리면.. 위에 어떤 메소드들을 구현해도 이것들을 구현안하면 돈이 얼마 있는지 확인만 할 수 있는겁니다.

2022-09-15 11:58 UTC, LesserJang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +    }
Vault API에서 말하는 Bank는 플레이어가 돈을 가질 수 있는지를 묻는게 아니라 진짜 '은행'과 '계좌'의 개념이 있는지를 체크하는 겁니다.

2022-09-15 12:13 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +        assert player != null;
넵 다음부터는 레서님께서 레서님께서 알려주신대로 assert를 알맞게 사용하도록 하겠습니다! 해당 메소드는 Deprecated 된 메소드여서 따로 수정은 하지 않겠습니다

2022-09-15 12:13 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +    }
제가 Vault API 사용법을 잘못 알고 있었군요.. 해당 메소드들을 구현하도록 하겠습니다.

2022-09-16 09:38 UTC, LesserJang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +    }
이것도 지워주셔야해요 은행 리스트를 반환하는거지 플레이어 이름들을 반환하는게 아니에요

2022-09-16 09:39 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/vault/EconomyManager.java
> +    }
수정하였습니다!

2022-09-16 09:41 UTC, LesserJang approved these changes

2022-09-16 09:42 UTC, merged