오프라인 상태인 플레이어의 돈 정보를 수정할 수 있도록 변경
MineFactory-Resource/Uconomy pull request #3
Opened 2022-09-07 14:07 UTC by Seokhun-Yang

테스트 케이스:
- moneydata.yml에 IamMinggu와 Kari_7280의 UUID만 있도록 설정하고 두 UUID의 값을 0으로 설정 후 테스트 시작

![image](https://user-images.githubusercontent.com/95516455/188897734-7d1d64d6-4149-4561-b735-4210db2c1d4f.png)

1. 오프라인 상태인 플레이어에게 돈을 보내기, 지급, 차감, 설정 그리고 돈 확인 해보기
2. 온라인 상태인 플레이어에게 1번과 똑같이 해보기
3. moneydata.yml에 존재하지 않는 UUID를 가진 플레이어에게 1번과 똑같이 해보기

![image](https://user-images.githubusercontent.com/95516455/188898116-245774ec-b350-48fc-9d66-f2f3e7cdbc96.png)

결과: moneydata.yml에 저장되어 있는 UUID를 가진 플레이어에게는 해당 플레이어가 온라인/오프라인 상태 상관없이 돈 정보를 정상적으로 수정할 수 있음. 만약, moneydata.yml에 저장되어 있지 않은 UUID를 가진 플레이어의 돈 정보를 수정하려고 할 경우 채팅에 "[알림] 입력하신 플레이어는 존재하지 않는 플레이어입니다." 메시지가 출력됨.

2022-09-08 09:43 UTC, LesserJang requested changes

2022-09-08 09:43 UTC, LesserJang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                        if (MoneyManager.get().getConfigurationSection("player").getKeys(false).contains(target.getUniqueId().toString())) {
모든 Key 값들을 가져와서 있는지 체크하기보다는 ConfigurationSection.isString() 메소드 같은걸로 확인하는게 더 좋을 것 같습니다

2022-09-08 09:43 UTC, LesserJang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                        OfflinePlayer target = Bukkit.getOfflinePlayer(args[1]);
getOfflinePlayer는 [JavaDocs](https://jd.papermc.io/paper/1.18/org/bukkit/Bukkit.html#getOfflinePlayer(java.lang.String))에 따르면 해당 서버에 접속하지 않은 닉네임을 가져오려 한다면 Mojang API를 통해 UUID를 가져오려고 시도하기 때문에 웹과 통신하는 시간동안 서버가 멈추게 됩니다. getOfflinePlayerIfCached 를 쓰시는게 더 좋을것같아요.

2022-09-08 09:43 UTC, LesserJang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                                        .replace("%name_of_player%", Objects.requireNonNull(target.getName()))
Objects.requireNonNull 은 모든 경우의 Null 체크의 해결책이 아닙니다. 해당 메소드는 null 이면 NPE를 던지는 메소드 입니다. 아마 서버에 접속하지 않은 오프라인 플레이어의 이름을 가져오려하면 Null 을 리턴하는 것 같은데, replace의 두번째 인자에 null 을 넣어서 NPE를 발생시키든, 해당 메소드를 사용해 NPE를 발생시키든 거기서 거기입니다.. if 문으로 null 체크 하는게 백배는 나아요.

2022-09-08 09:43 UTC, LesserJang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                                    .replace("%name_of_player%", Objects.requireNonNull(Bukkit.getOfflinePlayer(args[1]).getName()))
Bukkit.getOfflinePlayer 로 OfflinePlayer 를 변수에 어디 저장해놓고, 사용해주세요. 해당 메소드에서 어떻게 오프라인 플레이어를 가져오는지 모르는데 여러번 마구잡이로 실행시켜서 좋을 건 없을 것 같습니다.

2022-09-08 12:14 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                        if (MoneyManager.get().getConfigurationSection("player").getKeys(false).contains(target.getUniqueId().toString())) {
https://jd.papermc.io/paper/1.17/org/bukkit/configuration/MemorySection.html#getConfigurationSection(java.lang.String) 
에서 알아보니 isString() 메소드는 지정된 경로가 문자열인지 확인하는 메소드여서 특정 value가 있는지 확인하는 메소드인 isSet() 메소드를 사용하였습니다

2022-09-08 13:57 UTC, LesserJang commented
코드 쓰실 때 if 문 안에 if 문 넣는걸 반복하면 진짜 보기 힘들어져요.. 코드 가독성 문제라서 별로 상관 없기는 한데 그래도
```java
if (arg == null) {
    player.sendMessage("arg가 없어요");
    return;
}
```
이런식으로 쓰는게 더 가독성이 좋습니다.

2022-09-08 13:58 UTC, LesserJang approved these changes

2022-09-08 14:05 UTC, LesserJang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                                            Player onlineRecipient = Bukkit.getPlayer(args[1]);
recipient.getPlayer() 를 사용하는게 더 나을 것 같아요. 이름으로 플레이어 검색하는 것보다는 UUID 검색이 더 빠르죠.

2022-09-08 14:05 UTC, LesserJang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                        MoneyManager.get().set("player." + Bukkit.getOfflinePlayer(args[1]).getUniqueId(), increasedPlayerMoney);
여기 하나 안바꾸신것같아요.

2022-09-08 14:07 UTC, LesserJang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                                            String translatedMessages = transactionConfirmToRecipientMessages
변수명 작명하실때 너무 길게 쓰시는 것 같은데 이런건 그냥 for (String msg : msgList) 이런식으로 대충 알아볼 수 있게만 작명하시면 되요. 간결하고 알아보기 쉽게..!

2022-09-08 14:13 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                        MoneyManager.get().set("player." + Bukkit.getOfflinePlayer(args[1]).getUniqueId(), increasedPlayerMoney);
수정하도록 하겠습니다

2022-09-08 14:13 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                                            Player onlineRecipient = Bukkit.getPlayer(args[1]);
수정하도록 하겠습니다

2022-09-08 14:13 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +                                                            String translatedMessages = transactionConfirmToRecipientMessages
넵 다음부터는 간결하게 작성해보도록 하겠습니다

2022-09-08 14:33 UTC, tjrhuni commented
if문 가독성 좋게 수정해보도록 하겠습니다 감사합니당

2022-09-09 05:12 UTC, Fade-Jung approved these changes

2022-09-09 08:24 UTC, kari0707 approved these changes

2022-09-09 10:31 UTC, merged