데이터베이스 저장방식에 MYSQL 지원 추가하기
MineFactory-Resource/Uconomy pull request #6
Opened 2022-10-23 13:26 UTC by Seokhun-Yang

2022-10-27 08:11 UTC, LesserJang commented
데이터베이스를 메인 스레드에서 접근하면 데이터를 읽어들이는, 잠깐 blocking 되는 시간동안 서버 전체가 멈춰버려요. 무조건 비동기적으로 데이터베이스에 접근해야 됩니다. GunsCore의 스킨 데이터 경우는 서버에 플레이어가 접속하면 플레이어의 데이터를 비동기적으로 불러와서 캐시해두고, 필요할때마다 캐시에서 불러오는 방식을 사용하고 있어요. GunsCore의 데이터부분 참고하면서 만드시면 도움 되실 것 같아요.

2022-10-27 08:13 UTC, Seokhun-Yang commented
넵 GunsCore랑 CS 참고 하면서 비동기적으로 데이터베이스에 접근할 수 있도록 수정하겠습니다

2022-10-29 10:53 UTC, LesserJang requested changes

2022-10-29 10:53 UTC, LesserJang commented on src/main/java/net/teamuni/economy/hooks/UconomyPlaceholders.java
> +                return cacheIfPresent == null ? df.format(cacheUnchecked.getMoney()) : df.format(cacheIfPresent.getMoney());
구현이 뭔가 이상한것 같아요. 이렇게 되있으면 캐시가 이미 되어있든 되어있지 않든 getCache(UUID)에서 무조건 블로킹이 걸려버립니다.

2022-10-29 10:55 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/hooks/UconomyPlaceholders.java
> +                return cacheIfPresent == null ? df.format(cacheUnchecked.getMoney()) : df.format(cacheIfPresent.getMoney());
로그를 찍어보았는데, 서버 접속할 때 cacheUnchecked가 한 번 호출되고 그 다음에는 cacheIfPresent가 호출되는 것을 확인했습니다. cacheIfPresent만 사용하였을 때는 돈 관련 명령어를 한 번 입력해야 스코어보드에 정상적으로 업데이트가 되어서 위와 같이 코드를 작성하였습니다.

2022-10-30 02:18 UTC, LesserJang requested changes

2022-10-30 02:18 UTC, LesserJang commented on src/main/java/net/teamuni/economy/event/JoinEvent.java
> +            main.getPlayerDataManager().getCache(player.getUniqueId());
mysql 을 사용할때만 cache를 불러와야 합니다. 지금 구조가 mysql을 사용할때는 PlayerDataManager을 사용하고, 아닐때는 EconomyManager을 사용하고 있는데, 어짜피 둘다 돈 데이터를 저장하고 불러오는 공통의 기능을 인터페이스로 만들어두고 사용하는게 좋을 것 같아요. 자바의 객체지향중 다형성이라는 좋은 특징이 있는데 굳이 사용하지 않을 이유는 없어요.

2022-10-30 04:20 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/event/JoinEvent.java
> +            main.getPlayerDataManager().getCache(player.getUniqueId());
인터페이스는 생각을 못 하고 있었는데, 인터페이스로 한 번 구현해보도록 하겠습니다. 감사합니다!

2022-10-30 06:49 UTC, LesserJang approved these changes

2022-10-30 07:27 UTC, Fade-Jung approved these changes

2022-10-30 07:29 UTC, kari0707 approved these changes

2022-10-30 07:29 UTC, merged