Vault 플러그인 연동 해제
MineFactory-Resource/Uconomy pull request #7
Opened 2022-10-29 08:05 UTC by Seokhun-Yang

2022-11-05 14:55 UTC, LesserJang requested changes
지금 구조가 PlayerDataManager 클래스를 나눠버리니 MySQLDatabase에서 쓰이는 Statement 관련 클래스들이 PlayerDataManager 클래스에서도 쓰이기 시작했습니다. 클래스가 기능별로 잘 나눠져 있었는데, 그걸 흐트려버려서 어질러진 느낌이에요. 게다가 원래 구조가 PlayerDataManager에서는 YML 포맷의 데이터 처리, MySQLDatabase에서는 MySQL 데이터 처리로 나눠져 있었는데 MySQLDatabase를 냅둔채로 나눠버리니까 MySQLDatabase에는 그냥 히카리풀 객체만 담아두는 클래스로 변해버렸어요. 하고싶은 말은 PlayerDataManager과 MySQLDatabase가 하는일을 명확히 하는게 좋을 것 같아요. 지금 구조에서 겹치는 부분은 캐시 처리가 있고, 나뉘는 부분은 MySQL과 YML 데이터 처리죠? 제가 생각하기엔 캐시 처리를 PlayerDataManager라는 단일 객체에서 처리하고, MySQLDatabase와 YmlDatabase 로 나누어서 각각 데이터 처리만 담당하게 한 뒤, PlayerDataManager에서 Database 객체에 접근해서 캐시처리를 하게 해주면 좋을 것 같습니다.

2022-11-05 14:55 UTC, LesserJang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +    private PlayerDataManagerYML playerDataManagerYML;
인터페이스를 사용하는 가장 큰 이유가 같은 기능을 가지고 때에 따라 다른 클래스가 필요할때, 때에 따라서 클래스 한개를 생성해 변수에 넣어놓고, 때에 따라 다른 변수에 접근할 필요 없이 그냥 한 변수에서 꺼내서 쓰면 되는 편함입니다. 지금 여기선 MoneyUpdater 인터페이스를 상속하는 MySQL과 YML 클래스 두개가 모두 변수에 선언되어있는데, 그냥 MoneyUpdater 타입으로 변수를 선언하고, 필요에 따라서 MySQL이나 YML 클래스를 생성해서 변수에 넣어놓고 사용하는게 더 좋을 것 같습니다.

2022-11-05 15:22 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/Uconomy.java
> +    private PlayerDataManagerYML playerDataManagerYML;
남겨주신 코멘트를 꼼꼼히 읽어보았는데 레서님께서 말씀하신대로 수정하는 것이 좋을 것 같습니다. 자세하게 설명해주셔서 감사합니다!

2022-11-11 10:33 UTC, LesserJang approved these changes

2022-11-11 10:33 UTC, LesserJang commented on src/main/java/net/teamuni/economy/data/PlayerDataManager.java
> +                            if (updater == null) return;
&&로 묶어버립시다.

2022-11-11 11:11 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/economy/data/PlayerDataManager.java
> +                            if (updater == null) return;
둘 중 하나라도 null이면 통과하지 못 하여야하니까 | 를 쓰는게 맞지 않을까요?

2022-11-11 11:12 UTC, LesserJang commented on src/main/java/net/teamuni/economy/data/PlayerDataManager.java
> +                            if (updater == null) return;
아 맞아요 or로 묶어야해요

2022-11-11 11:24 UTC, kari0707 approved these changes

2022-11-11 11:29 UTC, Fade-Jung approved these changes

2022-11-11 11:30 UTC, merged